[package]
name = "blockchain-api"
version = "0.1.0"
edition = "2021"

[lib]
name = "blockchainlib"
path = "src/blockchain/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
crypto-hash = "0.3.4"